version: "3.8"

services:
  poller:
    build:
      context: ./services/poller
      dockerfile: Dockerfile
    network_mode: "host"
    restart: unless-stopped
    depends_on:
      - timescaledb
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: "12346"
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    volumes:
      - ./services/poller:/app

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: postgres
    ports:
      - "12346:5432"
    restart: unless-stopped
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

volumes:
  timescaledb-data: